eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10 # Intervalo para reintentos de fetch de la información del registro
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10 # Intervalo de latidos (default 30 segundos)
    lease-expiration-duration-in-seconds: 90 # Duración para que expire una instancia sin latidos (default 90 segundos)
